Vagrant.configure("2") do |config|
config.vm.define :servidor do |servidor|
servidor.vm.box = "bento/centos-7.9"
servidor.vm.network "public_network", ip: "172.168.1.11"
servidor.vm.hostname = "servidor"
end
end